services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_win_diet
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuaSenhaForte@2026
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - win-diet

networks:
  win-diet:
    driver: bridge

volumes:
  sqlserver_data: